name: Build

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build
    runs-on: [linux]
    steps:
      - name: git checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Build and analyze with SonarQube    
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
             node-version: '20' # or whatever version you need
      - run: npm install    # now npm commands will work

      - name: trivy install
        run: trivy fs . > trivyfs.txt
      - name: docker build and push for docker
        run: |
            docker build -t bhav .
            docker tag bhav ramesh2005/bhav:latest
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker push ramesh2005/bhav:latest
      - name: trivy scan
        run: trivy image ramesh2005/bhav:latest > trivyimage.txt
  deploy:
    needs: Build
    runs-on: [linux]
    steps:
      - name: docker pull image
        run: docker pull ramesh2005/bhav:latest
      - name: trivy scan
        run: trivy image ramesh2005/bhav:latest > trivyimagedeploy.txt
      - name: deploy to container
        run: docker run --name game -d -p 3000:3000 ramesh2005/bhav:latest
      - name: Update kubeconfig
        run: aws eks --region ap-south-1 update-kubeconfig --name EKS_CLOUD
      - name: Deploy to EKS
        run: kubectl apply -f deployment-service.yml  

 

                    
