name: Build

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build
    runs-on: [linux]
    steps:
      - name: git checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Build and analyze with SonarQube    
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
             node-version: '20' # or whatever version you need
      - run: npm install    # now npm commands will work

      - name: trivy install
        run: trivy fs . > trivyfs.txt
      - name: docker build and push for docker
        run: |
            docker build -t bhav .
            docker tag bhav ramesh2005/bhav:latest
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker push ramesh2005/bhav:latest
                

